CREATE TABLE sandbox_execution_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    project_version VARCHAR(64) NOT NULL,
    sandbox_step_set_digest VARCHAR(64) NOT NULL,
    confirmation_key VARCHAR(128) NOT NULL UNIQUE,
    confirmed_at TIMESTAMP NOT NULL,
    cancelled_at TIMESTAMP
);
CREATE INDEX idx_sandbox_confirmation_scope
    ON sandbox_execution_confirmations(user_id, project_id, plan_id);
