CREATE TABLE sandbox_execution_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT,
    execution_id VARCHAR(64) NOT NULL,
    plan_id BIGINT NOT NULL,
    step_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    lease_fence BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_digest VARCHAR(64) NOT NULL,
    project_version VARCHAR(64) NOT NULL,
    policy_digest VARCHAR(64) NOT NULL,
    request_json LONGTEXT NULL,
    status VARCHAR(32) NOT NULL,
    broker_execution_id VARCHAR(64) NULL,
    receipt_digest VARCHAR(64) NULL,
    receipt_json LONGTEXT NULL,
    error_code VARCHAR(64) NULL,
    dispatch_attempts INT NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    claim_owner VARCHAR(128) NULL,
    claim_token VARCHAR(64) NULL,
    claim_fence BIGINT NOT NULL DEFAULT 0,
    claim_expires_at DATETIME(6) NULL,
    retry_phase VARCHAR(16) NOT NULL DEFAULT 'DISPATCH',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sandbox_outbox_execution (execution_id),
    UNIQUE KEY uk_sandbox_outbox_idempotency (plan_id, idempotency_key),
    UNIQUE KEY uk_sandbox_outbox_step (plan_id, step_id),
    INDEX idx_sandbox_outbox_dispatch (status, next_attempt_at)
);
