package com.yanban.api.agent.sandbox;

public enum SandboxFailureCode {
    SANDBOX_DISABLED, SANDBOX_UNAVAILABLE, AUTHORITY_REJECTED, STALE_PROJECT_VERSION,
    INVALID_PATH, COMMAND_NOT_ALLOWED, ENV_NOT_ALLOWED, BUDGET_EXHAUSTED,
    CANCELLED, TIMED_OUT, LEASE_LOST, RECEIPT_CONFLICT, PROVIDER_REJECTED, CLEANUP_FAILED
}
