package com.yanban.sandbox.contract;
public enum SandboxExecutionStatus { ACCEPTED, CLAIMED, MATERIALIZING, CREATED, POLICY_APPLIED, RUNNING,
 SUCCEEDED_PENDING_CLEANUP, FAILED_PENDING_CLEANUP, CANCEL_REQUESTED, TIMED_OUT_PENDING_CLEANUP,
 CLEANING, SUCCEEDED, FAILED, CANCELLED, TIMED_OUT, CLEANUP_FAILED }
