package com.yanban.sandbox.contract;
public enum SandboxErrorCode { UNAUTHORIZED, DIGEST_CONFLICT, REQUEST_TOO_LARGE, CONCURRENCY_EXHAUSTED,
 PROVIDER_UNAVAILABLE, PROVIDER_REJECTED, POLICY_REJECTED, CANCELLED, TIMED_OUT, CLEANUP_FAILED, STALE_FENCE }
